import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const EXT_DIR = "node_modules/@plannotator/pi-extension";
const DIST_DIR = "dist";

async function build() {
    console.log("🚀 Building @gandazgul/plannotator-pi-extension-compiled...");

    if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR);

    const entrypoints = {
        "index.ts": "index.mjs",
        "server.ts": "server.mjs"
    };

    const externals = [
        "turndown",
        "@joplin/turndown-plugin-gfm",
        "@mariozechner/pi-coding-agent",
        "@mariozechner/pi-agent-core",
        "@mariozechner/pi-ai",
        "@mariozechner/pi-tui",
        "@openai/codex-sdk",
        "@anthropic-ai/claude-agent-sdk",
        "@opencode-ai/sdk"
    ];

    for (const [src, dest] of Object.entries(entrypoints)) {
        console.log(`Bundling ${src} -> ${dest}...`);
        const externalArgs = externals.map(e => `--external:${e}`).join(" ");
        
        execSync(`npx esbuild ${path.join(EXT_DIR, src)} --bundle --platform=node --format=esm --outfile=${path.join(DIST_DIR, dest)} ${externalArgs}`);

        // Patch bare Node imports for Deno and remove Node-only timeout calls
        const content = fs.readFileSync(path.join(DIST_DIR, dest), "utf8");
        const patchedImports = content.replace(
            /from "(fs|path|os|child_process|crypto|http|stream|net|url|util|events|buffer)"/g,
            'from "node:$1"',
        );

        // Deno's node:http compatibility does not implement ServerResponse#setTimeout
        // This call is used as a keep-alive hint in upstream code; removing it avoids runtime crashes.
        const patched = patchedImports.replace(/\bres\.setTimeout\(\s*0\s*\);?/g, "");

        fs.writeFileSync(path.join(DIST_DIR, dest), patched);
    }

    // Generate JS-accessible asset exports to avoid runtime filesystem coupling.
    const plannotatorHtml = fs.readFileSync(path.join(EXT_DIR, "plannotator.html"), "utf8");
    const assetsModulePath = path.join(DIST_DIR, "assets.mjs");
    fs.writeFileSync(
        assetsModulePath,
        [
            "// Auto-generated by build.mjs",
            `export const plannotatorHtml = ${JSON.stringify(plannotatorHtml)};`,
            "",
        ].join("\n"),
    );

    // Copy static assets for package consumers that still rely on file access.
    const assets = ["plannotator.html", "review-editor.html", "plannotator.json"];
    for (const asset of assets) {
        console.log(`Copying ${asset}...`);
        fs.copyFileSync(path.join(EXT_DIR, asset), path.join(process.cwd(), asset));
    }

    console.log("✅ Build complete!");
}

build().catch(console.error);
